# Generated by Django 5.2.8 on 2025-12-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationInfo',
            fields=[
                ('station_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('station_fullname', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'station_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationNeighbours',
            fields=[
                ('pk', models.CompositePrimaryKey('station_id', 'station_neighbour', blank=True, editable=False, primary_key=True, serialize=False)),
                ('station_id', models.CharField(max_length=4)),
                ('station_neighbour', models.CharField(max_length=4)),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'station_neighbours',
                'managed': False,
            },
        ),
    ]
