# Generated by Django 5.2.8 on 2026-03-13 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=500)),
                ('main_pic', models.URLField(blank=True, max_length=500)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('station', models.CharField(blank=True, max_length=100)),
                ('fee', models.CharField(blank=True, max_length=100)),
                ('open_hours', models.TextField(blank=True)),
                ('closed_on', models.CharField(blank=True, max_length=255)),
                ('short_desc', models.CharField(blank=True, max_length=500)),
                ('long_desc', models.TextField(blank=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_restaurants',
            },
        ),
    ]
