# Generated by Django 5.2.8 on 2026-03-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrestaurant',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
