# Generated by Django 5.2.8 on 2026-03-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_savedrestaurant_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrestaurant',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedrestaurant',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
