# Generated by Django 5.2.8 on 2026-03-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_savedrestaurant_short_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrestaurant',
            name='closed_on',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='savedrestaurant',
            name='fee',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='savedrestaurant',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='savedrestaurant',
            name='station',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
