# Generated by Django 5.2.8 on 2026-03-20 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_remove_savedrestaurant_users_usertorestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrestaurant',
            name='users',
            field=models.ManyToManyField(related_name='saved_restaurants', through='analysis.UserToRestaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='usertorestaurant',
            table='user_to_rest',
        ),
    ]
